full
ilyatsv/Converter pull request #3
Opened 2021-01-05 14:56 UTC by ilyatsv

PULL REQUEST with full code

2021-01-06 09:55 UTC, gmltA requested changes

2021-01-06 09:55 UTC, gmltA commented on app/src/basic/java/converter/Fragment_Buttons.java
> +    public ClipboardManager myClipboard;
You don't need this in basic version.

2021-01-06 09:55 UTC, gmltA commented on app/build.gradle
> +
See project requirements.

2021-01-06 09:55 UTC, gmltA commented on app/src/pro/java/converter/LogicVM.java
> +public class LogicVM extends ViewModel {
I don't quite understand. You have ViewModel only in the pro version?

2021-01-06 09:55 UTC, gmltA commented on app/src/pro/java/converter/LogicVM.java
> +    public float i;
?

2021-01-06 14:21 UTC, ilyatsv reviewed
fixes

2021-01-07 11:16 UTC, gmltA requested changes

2021-01-07 11:16 UTC, gmltA commented on app/src/basic/java/converter/LogicVM.java
> +    public float i;
???

2021-01-07 11:16 UTC, gmltA commented on app/src/pro/java/converter/Fragment_Buttons.java
> +public class Fragment_Buttons extends Fragment  {
The same code you have in basic version? Use inheritance to avoid duplication.

2021-01-07 12:37 UTC, ilyatsv commented on app/src/basic/java/converter/LogicVM.java
> +    public float i;
что здесь не так?

2021-01-07 13:02 UTC, ilyatsv commented on app/src/basic/java/converter/LogicVM.java
> +    public float i;
unitFrom -  это место по Х в таблице коэф
unitTo - это место по У там же
и я перевожу так значению

2021-01-07 13:12 UTC, ilyatsv reviewed
fixed duplication

2021-01-07 16:27 UTC, gmltA commented on app/src/basic/java/converter/LogicVM.java
> +    public float i;
`i` гэта што такое?

2021-01-07 16:49 UTC, ilyatsv reviewed
not used code

2021-01-07 17:11 UTC, gmltA approved these changes

2021-01-07 17:15 UTC, merged